---

# Repositorio do Google Chrome

- name: Importando a chave do repositorio do Google Chrome
  apt_key: 
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
  tags:
    - repo
    - chrome
    - web

- name: Adicionando o Repositorio do Google Chrome
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome
    update_cache: yes
  become: true
  tags:
    - repo
    - chrome
    - web


# Repositorio do Opera

- name: Importando a chave do repositorio do Opera
  apt_key: 
    url: https://deb.opera.com/archive.key
    state: present
  become: true
  tags:
    - repo
    - opera
    - web

- name: Adicionando o Repositorio do Opera
  apt_repository:
    repo: "deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free"
    state: present
    filename: opera
    update_cache: yes
  become: true
  tags:
    - repo
    - opera
    - web


# Repositorio do Vivaldi

- name: Importando a chave do repositorio do Vivaldi
  apt_key: 
    url: http://repo.vivaldi.com/stable/linux_signing_key.pub
    state: present
  become: true
  tags:
    - repo
    - vivaldi
    - web

- name: Adicionando o Repositorio do Vivaldi
  apt_repository:
    repo: "deb [arch=i386,amd64] http://repo.vivaldi.com/stable/deb/ stable main"
    state: present
    filename: vivaldi
    update_cache: yes
  become: true
  tags:
    - repo
    - vivaldi
    - web


# Repositorio do Skype

- name: Importando a chave do repositorio do Skype
  apt_key: 
    url: https://repo.skype.com/data/SKYPE-GPG-KEY
    state: present
  become: true
  tags:
    - repo
    - skype

- name: Adicionando o Repositorio do Skype
  apt_repository:
    repo: "deb https://repo.skype.com/deb stable main"
    state: present
    filename: skype
    update_cache: yes
  become: true
  tags:
    - repo
    - skype

# Repositorio do Visual Studio Code

- name: Importando a chave do repositorio do Visual Studio Code
  apt_key: 
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  tags:
    - repo
    - vscode
    - dev

- name: Adicionando o Repositorio do Visual Studio Code
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    filename: vscode
    update_cache: yes
  become: true
  tags:
    - repo
    - vscode
    - dev
