---

# Instalação do Docker

- name: Importando a chave do repositorio do Docker para O Debian ou Ubuntu
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt_key: 
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  become: true
  tags:
    - docker

- name: Importando a chave do repositorio do Docker para o Linux Mint
  when: ansible_distribution == "Linux Mint"
  apt_key: 
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: true
  tags:
    - docker

- name: Adicionando o Repositorio do Docker
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes
  become: true
  tags:
    - docker

- name: Adicionando o Repositorio do Docker para o Linux Mint 18
  when: ansible_distribution == "Linux Mint" and ansible_distribution_major_version == "18"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    filename: docker
    update_cache: yes
  become: true
  tags:
    - docker

- name: Adicionando o Repositorio do Docker para o Linux Mint 19
  when: ansible_distribution == "Linux Mint" and ansible_distribution_major_version == "19"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker
    update_cache: yes
  become: true
  tags:
    - docker

- name: Instalando o Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  notify:
    - Adicionando usuario ao grupo 'docker'
  become: true
  tags:
    - docker

- name: Instalando o Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x
  become: true
  tags:
    - docker-compose
