---


# Atualizando todos os pacotes


- name: "Atualizando apt cache"
  apt: 
    update_cache: yes 
    cache_valid_time: 7200
  become: true
  tags:
    - repo


- name: Atualizando todos os pacotes
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
  become: true
  tags:
    - repo
    - update

# Pacotes essenciais

- name: Instalando os pacotes essenciais
  apt:
    name: "{{ pacotes_essenciais }}"
    state: present
  become: true
  tags:
    - default


# Pacotes de Codec

- name: Instalando os pacotes de codecs
  apt:
    name: "{{ pacotes_codec }}"
    state: present
  become: true
  tags:
    - codecs

# Copiando o script de updates

- name: "Copiando o script de atualização de S.O."
  copy:
    src: "debian_like/update.sh"
    dest: "{{ ansible_user_dir }}/update.sh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: "a+x"
  tags:
    - default