---

# Adicionando os repositorios do rpmfusion

- name: Adicionando o repositorio do rpmfusion free
  dnf:
    name: "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - repo
    - rpmfusion
    - extras

- name: Adicionando o repositorio do rpmfusion nonfree
  dnf:
    name: "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - repo
    - rpmfusion
    - extras

# Importando as chaves dos repositorios do rpmfusion

- name: Importando a chave do repositorio do rpmfusion free
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"
    state: present
  become: true
  tags:
    - repo
    - rpmfusion
    - extras

- name: Importando a chave GPG do repositorio do rpmfusion nonfree
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"
    state: present
  become: true
  tags:
    - repo
    - rpmfusion
    - extras

# Adicionando o repositorio do Google Chrome

- name: Importando a chave do repositorio do Google Chrome
  rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
  tags:
    - repo
    - chrome
    - web

- name: Copiando arquivo de reposit贸rio do Google Chrome
  copy:
    src: google-chrome-rpm.repo
    dest: /etc/yum.repos.d/google-chrome.repo
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - repo
    - chrome
    - web


# Adicionando o repositorio do Opera

- name: Importando a chave do repositorio do Opera
  rpm_key:
    key: https://rpm.opera.com/rpmrepo.key
    state: present
  become: true

- name: Copiando arquivo de reposit贸rio do Opera
  copy:
    src: opera-rpm.repo
    dest: /etc/yum.repos.d/opera.repo
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - repo
    - opera
    - web

# Adicionando o repositorio do Vivaldi

- name: Importando a chave do repositorio do Vivaldi
  rpm_key:
    key: http://repo.vivaldi.com/archive/linux_signing_key.pub
    state: present
  become: true
  tags:
    - repo
    - vivaldi
    - web

- name: Copiando arquivo de reposit贸rio do Vivaldi
  copy:
    src: vivaldi-rpm.repo
    dest: /etc/yum.repos.d/vivaldi.repo
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - repo
    - vivaldi
    - web

# Instalando o Skype

- name: Importando a chave GPG do repositorio do Skype
  rpm_key:
    key: https://repo.skype.com/data/SKYPE-GPG-KEY 
    state: present
    validate_certs: no
  become: true
  tags:
    - repo
    - skype

- name: Baixando o binario do Skype
  get_url:
    url: "https://repo.skype.com/data/skype-stable.repo"
    dest: "/etc/yum.repos.d/skype-stable.repo"
    validate_certs: no
  become: true
  tags:
    - repo
    - skype


# Adicionando o repositorio do Visual Studio Code

- name: Importando a chave do repositorio do Visual Studio Code
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  tags:
    - repo
    - vscode
    - dev

- name: Copiando arquivo de reposit贸rio do Visual Studio Code
  copy:
    src: vscode-rpm.repo
    dest: /etc/yum.repos.d/vscode.repo
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - repo
    - vscode
    - dev
