---

# Adicionando os repositorios do rpmfusion

- name: Adicionando o repositorio do rpmfusion free
  dnf:
    name: "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - repo
    - rpmfusion
    - extras

- name: Adicionando o repositorio do rpmfusion nonfree
  dnf:
    name: "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - repo
    - rpmfusion
    - extras

# Importando as chaves dos repositorios do rpmfusion

- name: Importando a chave do repositorio do rpmfusion free
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"
    state: present
  become: true
  tags:
    - repo
    - rpmfusion
    - extras

- name: Importando a chave GPG do repositorio do rpmfusion nonfree
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"
    state: present
  become: true
  tags:
    - repo
    - rpmfusion
    - extras
