---

# Atualizar todos os pacotes

- name: Atualizando todos os pacotes
  dnf:
    name: "*"
    state: latest
  become: true
  tags:
    - repo
    - update

# Verificando se existe KDE Plasma

- name: Verificando se existe KDE Plasma
  shell: test -f {{ ansible_user_dir }}/.config/plasma-nm
  ignore_errors: yes 
  register: iskde
  tags:
    - default

# Instalando os pacotes enssenciais

- name: Instalando pacotes essenciais
  dnf:
    name: "{{ pacotes_essenciais }}"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - default

# Instalando os pacotes do Gnome

- name: Adicionando pacotes do Gnome
  when: iskde.rc == 1
  dnf:
    name: "{{ pacotes_gnome }}"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - default

  # Instalando os pacotes do KDE

- name: Adicionando pacotes do KDE Plasma
  when: iskde.rc == 0
  dnf:
    name: "{{ pacotes_kde }}"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - default

# Instalando os codecs

- name: Instalando codecs
  dnf:
    name: "{{ pacotes_codec }}"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - codecs
