---


# Realizando o dist-upgrade

- name: Realizando o dist-upgrade
  zypper:
    name: '*'
    state: dist-upgrade
    update_cache: yes
  become: true
  tags:
    - repo
    - update


# Realizando o dist-upgrade

- name: Realizando o Update
  zypper:
    name: '*'
    state: latest
  become: true
  tags:
    - repo
    - update


# Instalando pacotes essenciais

- name: Instalando pacotes essenciais
  zypper:
    name: "{{ pacotes_essenciais }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - default

# Instalando pacotes de codecs

- name: Instalando pacotes de codecs
  zypper:
    name: "{{ pacotes_codecs }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - codecs

# Copiando o script de updates

- name: "Copiando o script de atualização de S.O."
  copy:
    src: "opensuse/update.sh"
    dest: "{{ ansible_user_dir }}/update.sh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_real_group_id }}"
    mode: "a+x"
  tags:
    - default