---

# Realizando o dist-upgrade

- name: Realizando o dist-upgrade
  zypper:
    name: '*'
    state: dist-upgrade
    update_cache: yes
  become: true
  tags:
    - repo
    - update

# Instalando pacotes essenciais

- name: Instalando pacotes essenciais
  zypper:
    name: "{{ pacotes_essenciais }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - default

# Instalando pacotes de codecs

- name: Instalando pacotes de codecs
  zypper:
    name: "{{ pacotes_codecs }}"
    state: present
    update_cache: yes
  become: true
  tags:
    - codecs
